In [1]:
import pandas as pd

In [36]:
cast = pd.read_csv("C:/Users/DIBYAJIT/OneDrive/Desktop/Top Mentor/Advanced Modules and MySQL/Assignment/File/cast/cast.csv")
cast.head(10)

,title,year,name,type,character,n
0,Closet Monster,2015.0,Buffy #1,actor,Buffy 4,NaN
1,Suuri illusioni,1985.0,Homo $,actor,Guests,22.0
2,Battle of the Sexes,2017.0,$hutter,actor,Bobby Riggs Fan,10.0
3,Secret in Their Eyes,2015.0,$hutter,actor,2002 Dodger Fan,NaN
4,Steve Jobs,2015.0,$hutter,actor,1988 Opera House Patron,NaN
5,Straight Outta Compton,2015.0,$hutter,actor,Club Patron,NaN
6,Straight Outta Compton,2015.0,$hutter,actor,Dopeman,NaN
7,For Thy Love 2,2009.0,Bee Moe $lim,actor,Thug 1,NaN
8,"Lapis, Ballpen at Diploma, a True to Life Journey",2014.0,Jori ' Danilo' Jurado Jr.,actor,Jaime (young),9.0
9,Desire (III),2014.0,Syaiful 'Ariffin,actor,Actor Playing Eteocles from 'Antigone',NaN

### How many movies are listed in the titles dataframe?

In [5]:
print (cast['title'].nunique())

166670

print (cast['title'].unique())

### What are the earliest two films listed in the titles dataframe?

In [15]:
earliest_film = cast.sort_values('year', ascending = True )
earliest_film.iloc [0:2]

,title,year,name,type,character,n
555929,Miss Jerry,1894.0,Chauncey Depew,actor,Himself - the Director of the New York Central...,NaN
464860,Miss Jerry,1894.0,William Courtenay,actor,Mr. Hamilton,NaN

### How many movies have the title "Hamlet"?

In [94]:
cast[cast ['title'] == 'Hamlet'].count

<bound method DataFrame.count of           title    year              name   type              character     n
1615     Hamlet  1996.0        Riz Abbasi  actor  Attendant to Claudius   1.0
7438     Hamlet  1921.0  Fritz Achterberg  actor            Fortinbras,   9.0
11242    Hamlet  2009.0      Hayden Adams  actor                Laertes   7.0
11243    Hamlet  2009.0      Hayden Adams  actor                 Player   7.0
13907    Hamlet  1913.0       Eric Adeney  actor               Reynaldo  14.0
...         ...     ...               ...    ...                    ...   ...
2113683  Hamlet  2015.0         Ben Stott  actor           Player Queen  12.0
2133184  Hamlet  2011.0   Haig Sutherland  actor                Laertes   NaN
2139408  Hamlet  1948.0      Basil Sydney  actor    Claudius - The King  11.0
2141264  Hamlet  1996.0   Thomas Szekeres  actor           Young Hamlet  41.0
2157738  Hamlet  1948.0       Tony Tarver  actor           Player Queen   7.0

[218 rows x 6 columns]>

In [ ]:
## 218 movies have the title as "Hamlet"

### How many movies are titled "North by Northwest"?

In [20]:
cast[cast['title'] == 'North by Northwest'].shape

(81, 6)

In [ ]:
## 81 movies are titles 'North by Northwest'

### When was the first movie titled "Hamlet" made?

In [34]:
a = earliest_film[earliest_film ['title'] == 'Hamlet']
a.iloc[0:1, [0,1]]

          title    year
1545289  Hamlet  1910.0

### List all of the "Treasure Island" movies from earliest to most recent.

In [39]:
earliest_film[earliest_film['title'] == 'Treasure Island']

,title,year,name,type,character,n
339256,Treasure Island,1918.0,Francis Carpenter,actor,Jim Hawkins,1.0
830114,Treasure Island,1918.0,Charles Gorman,actor,Prologue Player,NaN
1261579,Treasure Island,1918.0,Raymond Lee,actor,Bit Role,NaN
1715014,Treasure Island,1918.0,Lloyd Perl,actor,Black Dog,4.0
840745,Treasure Island,1918.0,Joe Grant,actor,Undetermined child role,NaN
...,...,...,...,...,...,...
589900,Treasure Island,1999.0,Jamie Donovan,actor,John,21.0
1959741,Treasure Island,1999.0,Richard Schave,actor,Man,21.0
1375015,Treasure Island,1999.0,J.P. Manoux,actor,Officer Hughes,18.0
934507,Treasure Island,1999.0,Pat Healy,actor,Clark,4.0
1637661,Treasure Island,1999.0,Nick Offerman,actor,Samuel,2.0

### How many movies were made in the year 1950?

In [42]:
cast [cast['year'] == 1950].shape

(14653, 6)

### How many movies were made in the year 1960?

In [43]:
cast [cast ['year'] == 1960].shape

(11551, 6)

### How many movies were made from 1950 through 1959?

In [44]:
cast [cast ['year'].between (1950,1959)].shape

(137408, 6)

### In what years has a movie titled "Batman" been released?

In [47]:
cast[cast['title'] == 'Batman'].iloc [:,[0,1]]

          title    year
95672    Batman  1943.0
96186    Batman  1943.0
114034   Batman  1989.0
119476   Batman  1989.0
149767   Batman  1989.0
...         ...     ...
2068050  Batman  1989.0
2096318  Batman  1989.0
2099960  Batman  1989.0
2115809  Batman  1989.0
2152546  Batman  1989.0

[89 rows x 2 columns]

### How many roles were there in the movie "Inception"?

In [55]:
cast [cast ['title'] == 'Inception']['character'].nunique()

42

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [77]:
i = cast[cast['title']=='Inception']
i_no_n = i['n'].isnull().sum()
print (i_no_n)

21

### But how many roles in the movie "Inception" did receive an "n" value?

In [81]:
print (i['n'].count()) # i  is the previous variable

31

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [95]:
n_sorted = cast.sort_values ('n', ascending = True).dropna()
n1 = n_sorted [n_sorted ['title'] == 'North by Northwest']
n1.iloc [::,[0,4,5]]

                      title                    character     n
840374   North by Northwest           Roger O. Thornhill   1.0
1404704  North by Northwest              Phillip Vandamm   3.0
343701   North by Northwest                The Professor   5.0
1634552  North by Northwest              Lester Townsend   7.0
1229083  North by Northwest                      Leonard   8.0
1746383  North by Northwest              Victor Larrabee  10.0
642085   North by Northwest                        Licht  11.0
447893   North by Northwest                    Dr. Cross  13.0
1454363  North by Northwest               Sergeant Flamm  14.0
198496   North by Northwest               Captain Junket  15.0
1334726  North by Northwest  Charley - Chicago Policeman  16.0

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [84]:
n_sorted = cast.sort_values ('n', ascending = True)
cast_sleuth = n_sorted [n_sorted ['title'] == 'Sleuth']
cast_sleuth_1972 = cast_sleuth [cast_sleuth['year'] == 1972]
cast_sleuth_1972.iloc [::, [0,1,4,5]]

          title    year                   character    n
1644328  Sleuth  1972.0                 Andrew Wyke  1.0
314691   Sleuth  1972.0                 Milo Tindle  2.0
360365   Sleuth  1972.0           Inspector Doppler  3.0
1412647  Sleuth  1972.0  Detective Sergeant Tarrant  4.0
1396572  Sleuth  1972.0      Police Constable Higgs  6.0

### Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [85]:
cast_sleuth_2007 = cast_sleuth [cast_sleuth['year'] == 2007]
cast_sleuth_2007.iloc [::, [0,1,4,5]]

          title    year          character    n
314692   Sleuth  2007.0             Andrew  1.0
1246855  Sleuth  2007.0               Milo  2.0
1741124  Sleuth  2007.0        Man on T.V.  3.0
250297   Sleuth  2007.0  Other Man on T.V.  NaN
360366   Sleuth  2007.0  Inspector Doppler  NaN

### How many roles were credited in the silent 1921 version of Hamlet?

In [104]:
n_s_na = cast.sort_values('n',ascending  = True).dropna()
n_hamlet = n_s_na [n_s_na ['title'] == 'Hamlet']
n_h_1921 = n_hamlet [n_hamlet ['year'] == 1921]
print (n_h_1921.iloc [::, [0,1,4,5]])
print (n_h_1921 ['n'].count ())

          title    year     character    n
442224   Hamlet  1921.0  K?nig Hamlet  2.0
2106367  Hamlet  1921.0       Horatio  5.0
1095274  Hamlet  1921.0      Polonius  6.0
535307   Hamlet  1921.0       Laertes  7.0
7438     Hamlet  1921.0   Fortinbras,  9.0
5

### How many roles were credited in Branagh’s 1996 Hamlet?

In [105]:
n_h_1996 = n_hamlet [n_hamlet ['year'] ==  1996]
print (n_h_1996.iloc [::, [0,1,4,5]])
print (n_h_1996 ['n'].count ())

          title    year                 character     n
1615     Hamlet  1996.0     Attendant to Claudius   1.0
92106    Hamlet  1996.0        English Ambassador   2.0
206181   Hamlet  1996.0     Attendant to Claudius   3.0
211111   Hamlet  1996.0  Ghost of Hamlet's Father   4.0
250281   Hamlet  1996.0                    Hamlet   5.0
262368   Hamlet  1996.0                  Polonius   6.0
283598   Hamlet  1996.0                    Priest   7.0
307699   Hamlet  1996.0     Attendant to Claudius   8.0
482982   Hamlet  1996.0         First Gravedigger  10.0
500005   Hamlet  1996.0             Stage Manager  11.0
555725   Hamlet  1996.0                  Reynaldo  13.0
577284   Hamlet  1996.0              Guildenstern  14.0
582748   Hamlet  1996.0                    Yorick  15.0
633587   Hamlet  1996.0                  Lucianus  17.0
679290   Hamlet  1996.0                   Horatio  18.0
683298   Hamlet  1996.0                 Francisco  19.0
797642   Hamlet  1996.0                     Priam  21.0
955936   Hamlet  1996.0               Player King  23.0
1037016  Hamlet  1996.0                 Cornelius  24.0
1044207  Hamlet  1996.0                  Claudius  25.0
1167241  Hamlet  1996.0      Fortinbras's Captain  27.0
1269051  Hamlet  1996.0                 Marcellus  29.0
1435643  Hamlet  1996.0                  Barnardo  30.0
1366209  Hamlet  1996.0                   Laertes  31.0
2076719  Hamlet  1996.0      Fortinbras's Captain  32.0
1493790  Hamlet  1996.0                Old Norway  33.0
1500413  Hamlet  1996.0                Sailor Two  34.0
152349   Hamlet  1996.0        Second Gravedigger  37.0
1966605  Hamlet  1996.0                Young Lord  38.0
1993152  Hamlet  1996.0                Fortinbras  39.0
2073370  Hamlet  1996.0               Rosencrantz  40.0
2141264  Hamlet  1996.0              Young Hamlet  41.0
32

### How many "Hamlet" roles have been listed in all film credits through history?

In [107]:
print (n_hamlet['n'].count())

168

### How many people have played an "Ophelia"?

In [114]:
c_ophelia = cast [cast ['character'] == 'Ophelia']
print (c_ophelia ['name'].unique() )
print (c_ophelia ['name'].nunique() )

['Amy Bourque' 'Josie Chisholm' 'Crystal Cordero' 'Lucas Grabeel'
 'Catherine (IV) Lord' 'Justine Mooritz' 'Hannah Elizabeth Smith']
7

### How many people have played a role called "The Dude"?

In [119]:
c_TD = cast [cast ['character'] == 'The Dude']
print (c_TD['name'].unique())
print (c_TD['name'].nunique())

['Jeff Bridges' 'Jordan Cann' 'Scott Crowell' 'Chris DeMarcus'
 'Mike Donlin' 'Devin The Dude' 'Matthew (XIX) James' 'Christopher Kadish'
 'Jason Loughridge' 'Steve Lyons' 'Mark Alan Meek' 'Jerry Miley'
 'House Peters Jr.' 'Thomas (VIII) Porter' 'Jason Priestley'
 'Bobby Styles']
16

### How many people have played a role called "The Stranger"?

In [121]:
c_ts = cast [cast ['character'] == 'The Stranger']
print (c_ts ['name'].unique ())
print (c_ts ['name'].nunique())

['Hassan Mutlag Al-Maraiyeh' 'Vincent H. Alexander' 'Tony Anthony'
 'Phil Arnold' 'Ryan Andrew Balas' 'Cristi Balea' 'Richard Baron'
 'Nigel Barrett' 'Harry Basch' 'Arben Biba' 'Richard (XV) Bishop'
 'Frank Borzage' 'Pinkas Braun' 'Gerard Butler' 'Nicholas Campbell'
 'Nik Catello' 'Lyster Chambers' 'Michael V. Chastain' 'Chazz'
 'Alan Christy' 'Jason (VII) Coleman' 'Hallam Cooley' 'Sharlto Copley'
 'Ste Cork' 'Gino Corrado' 'Harp Corrigan' 'Walter Coy' 'Shawn Crosby'
 'Jemo Dalipovic' 'Matt Danner' 'Helmut Dantine' 'Josh Davidson'
 'William B. Davidson' 'Jim Davis' 'Ben (V) Dawson' 'Michael Dawu'
 'Tim DeKay' 'Patrick Dempsey' 'Joe DeRita' 'Alex Diakun' 'Billy Drago'
 'Tex Driscoll' 'Rainer D?sing' 'Eddie Eagle' 'Clint Eastwood'
 'James L. Edwards' 'Sam Elliott' 'Alberto Esparza' 'Manuchehr Farid'
 'Michael Ian Farrell' 'George Fawcett' 'Federico Fellini'
 'James Stephen Finn' "Maurice 'Lefty' Flynn" 'Johnston Forbes-Robertson'
 'Francis Ford' 'Ben Foster' 'Robert Frazer' 'Ralph (II) Freedman'
 'Mark Fucile' 'Courtney Gains' 'J?zsef Gallai' 'Sammy Gilbert'
 'J.H. Gilmour' 'Josue Guerra' 'Sid Haig' 'Jenny Haining'
 'Justin (VIII) Hall' 'C.M. Hallard' 'Troy Halverson' 'Gunnar (II) Hansen'
 'Ty Hardin' 'Michael Harrelson' 'Jonathan Haug' 'Edward Hearn'
 'Lance Henriksen' 'Dan Hicks' 'George Hilton' 'Lee Horsley'
 'Kevin Howarth' 'Chad (XIII) Johnson' 'Jeff Joslin' 'Axel Kaae'
 'Manav Kaushik' 'Michael Kennelty' 'Charles Kent' 'Irwin Keyes'
 'Udo Kier' 'Andrew (II) Kines' 'William Kozy' 'Jun Kunimura'
 'Darwin Lamb' 'Mike (VI) Lambert' 'C.S. Lee' 'Nick Leos'
 'Joseph Levering' 'Elmo Lincoln' 'Lucien Littlefield'
 'Andrew Espinoza Long' 'Peter Lorre' 'Wallace MacDonald' 'D.G. Maloney'
 'Nick Mancuso' 'Marilyn Manson' 'Ed Mantell' 'Bruce Marchiano'
 'Mike (III) Marino' 'Tully Marshall' 'John Wills Martin' 'Kingsly Martin'
 'Ryan McGivern' 'Aaron McGrane' 'Richard (II) McNamara' 'Tomas Milian'
 'Jefferson Moore' 'John (III) Moore' 'Matthew Moy' 'Uns Mufti'
 'Morgan Muscat' 'Timothy Muskatell' 'Wade Mylius' 'Steve Noettl'
 'Michael (III) Nolan' 'Ken Nordine' 'Harry Northrup' 'Bill Oberst Jr.'
 'Ricky Onsgard' 'Deobia Oparei' 'William Orlamond' 'Michael Otis'
 'Gary (III) Owen' 'Anthony Oyeola' 'Bradley Page' 'Michael Pasternak'
 'Bill Patton' 'Frantisek Paul' 'George C. Pearce' 'Jack Perrin'
 'Ralph Peters' 'William Pike' 'Purnell Pratt' 'Wojciech Pszoniak'
 'John Qualen' 'Randy Raphael' 'Matthew Rauch' 'Jake Red'
 'Shivam Reddington' 'Brad Renfro' 'Alveraz Ricardez'
 'Steven (II) Richards' 'Darren Ripley' 'Tim Robbins' 'North Roberts'
 'Karel Roden' 'Don Rowe' 'Aleksandr Rumnyov' 'Philippe Saba'
 'Monroe Salisbury' 'Matthew Luke Sandoval' 'Martin Sheen'
 'George Shevtsov' 'Bernard Siegel' 'Joe Sinclitico' 'Gustaf Skarsg?rd'
 'Robert Skene' 'Herb Smith' 'Kevin Sorbo' 'Ron (III) Spencer'
 'Marco St. John' 'David Strathairn' 'Leonard Strong' 'Suman'
 'Kiefer Sutherland']
173

### How many roles has Sidney Poitier played throughout his career?

In [122]:
c_sp = cast[cast ['name'] == 'Sidney Poitier']
print (c_sp['character'].unique())
print (c_sp ['character'].nunique())

['Gordon Ralfe' 'Manny Durrell' 'Walter Lee Younger' 'Dr. Matt Younger'
 'Sgt. Eddie Towler' 'Rau-Ru' 'Gregory W. Miller' 'John Kane' 'Buck'
 'Reverend Msimangu' 'Toller' 'Tommy Tyler' 'Jack Parks' 'Inman Jackson'
 'Gates Watson' 'John Prentice' 'Virgil Tibbs' 'Clyde Williams'
 'Homer Smith' 'Roy Parmenter' 'Dr. Luther Brooks' 'Eddie Cook' 'Porgy'
 'Doctor' 'Robertson' 'Night Club Extra' 'Warren Stantin' 'Donald Crease'
 'Kimani Wa Karanja' 'Ben Munceford' 'Noah Cullen' 'Simon of Cyrene'
 'FBI Deputy Director Carter Preston' 'Aly Mansuh' 'Jason Higgs' 'Obam'
 'Alan Newell' 'Shack Twala' 'Mark Thackeray' 'Steve Jackson' 'Marcus']
41

### How many roles has Judi Dench played?

In [123]:
c_jd = cast[cast ['name'] == 'Judi Dench']
print (c_jd['character'].unique())
print (c_jd ['character'].nunique())

[]
0

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [129]:
y_sort = cast.sort_values ('year', ascending = True)
y_1940 = y_sort[y_sort ['year'].between (1940,1949)]
y_1940_2 = y_1940[y_1940['n'] == 2]
y3 = y_1940_2[y_1940_2['name'] == 'Cary Grant']
y3.iloc [::,[0,1,2,3,4,5]]

                   title    year        name   type    character    n
840371  My Favorite Wife  1940.0  Cary Grant  actor         Nick  2.0
840381    Penny Serenade  1941.0  Cary Grant  actor  Roger Adams  2.0

### List the leading roles that Cary Grant played in the 1940s in order by year.

In [136]:
y_cg = y_1940[y_1940['name'] == 'Cary Grant']
y_cg1 = y_cg [y_cg ['n'] == 1]
print (y_cg1.iloc [::, [0,1,4]])

                                       title    year              character
840353                       His Girl Friday  1940.0           Walter Burns
840397               The Howards of Virginia  1940.0            Matt Howard
840399                The Philadelphia Story  1940.0     C. K. Dexter Haven
840386                             Suspicion  1941.0                Johnnie
840401                  The Talk of the Town  1942.0           Leopold Dilg
840377                 Once Upon a Honeymoon  1942.0  Patrick 'Pat' O'Toole
840344                     Destination Tokyo  1943.0          Capt. Cassidy
840370                             Mr. Lucky  1943.0        Joe Bascopolous
840369                             Mr. Lucky  1943.0              Joe Adams
840378                      Once Upon a Time  1944.0            Jerry Flynn
840336                  Arsenic and Old Lace  1944.0      Mortimer Brewster
840373             None But the Lonely Heart  1944.0             Ernie Mott
840375                             Notorious  1946.0                 Devlin
840372                         Night and Day  1946.0            Cole Porter
840394                     The Bishop's Wife  1947.0                 Dudley
840393      The Bachelor and the Bobby-Soxer  1947.0            Dick Nugent
840368  Mr. Blandings Builds His Dream House  1948.0          Jim Blandings
840348          Every Girl Should Be Married  1948.0      Dr. Madison Brown
840357                I Was a Male War Bride  1949.0  Captain Henri Rochard

### How many roles were available for actors in the 1950s?

In [132]:
c_50s = cast [cast ['year'].between (1951,1959)]
print (c_50s['character'].count())

122755

### How many roles were available for actresses in the 1950s?

### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [138]:
y = cast.sort_values ('year', ascending = True)
y2 = y[y['year'].between (1894,1980)]
print (y2['character'].unique())
print (y2['character'].nunique())

['Himself - the Director of the New York Central Railroad' 'Mr. Hamilton'
 'Lion' ... 'Prof. Tsuchiya' 'Sardara' 'Tsong']
388767

### How many non-leading roles were available through from the beginning of film history through 1980?

In [139]:
y2_n = y2[y2['n'] != 1]
print (y2_n['character'].unique())
print (y2_n['character'].nunique())

['Himself - the Director of the New York Central Railroad' 'Mr. Hamilton'
 'Lion' ... 'Prof. Tsuchiya' 'Sardara' 'Tsong']
364422


### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [148]:
o = cast [(cast ['n'].isna()) & (cast ['year'] <= 1980)]
o['n'].shape[0]

299849

In [147]:
cast.value_counts(dropna = False)

title                     year    name                     type   character           n
Eskimo Limon              1978.0  Jonathan Sagall          actor  Momo                3.0     2
August (III)              2011.0  George Barbakadze        actor  Background          82.0    2
Gold                      2016.0  Jameson Macmillan        actor  Motel Guest         NaN     2
Fucking My Way Back Home  2016.0  Julio Benitez Guardiola  actor  Alberto             3.0     2
Angoor                    1982.0  Sanjeev Kumar            actor  Ashok               1.0     2
                                                                                             ..
NaN                       2015.0  Elijah Meyer             actor  Landen's Friend     NaN     1
                                  Emma (V) Meyer           actor  Brock's Girlfriend  NaN     1
                                  Gabriel (II) Michael     actor  Psychopath          NaN     1
                                  Israel Adam              actor  Landen's Friend #2  NaN     1
                                  Landen James             actor  Landen              NaN     1
Name: count, Length: 2159928, dtype: int64